-- V20__fix_schema_alignment.sql
-- No-op on a from-scratch Flyway apply. Every change here was already made by
-- earlier migrations: import_batch_id + duplicate_candidates (V14), resolution_data
-- (V12), quality_score/quality_tier and the entity_resolution_cache table (V15),
-- completeness/resolution_confidence/source_quality/validation_score (V16).
-- Originally a drift-reconciliation for databases migrated by the legacy tool;
-- retained for version continuity. See TRACK-110 / ADR-013.
